config_builder:
  enabled: true
  script: |
    #! /usr/bin/env bash
    echo '{"engine": {"name": "tofu"}, "workflows": [{"tag_query": "dir:tf1", "runs_on": "ubuntu-latest"}, {"tag_query": "dir:tf2", "runs_on": ["ubuntu-latest"]}]}'

engine:
  name: tofu
workflows:
- runs_on: ubuntu-latest
  tag_query: dir:tf1
- runs_on: [ubuntu-latest]
  tag_query: dir:tf2
